services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.devenvironment
    container_name: coboldevenv
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: coboldevenvdb
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initsql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres-data:

